- id: 200
  key: satoshi
  currency: btc
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 400
  key: bank
  currency: aud
  sort_order: 2
  bank_accounts:
    -
      bank: 'ANZ'
      branch: '4000'
      holder: 'Felipe Caldas'
      account: '1230120123'
