- id: btcaud
  code: 3
  #name: BTC/AUD      # default name
  base_unit: btc
  quote_unit: aud
  #price_group_fixed: 1 # aggregate price levels in orderbook
  bid: {fee: 0, currency: aud, fixed: 2}
  ask: {fee: 0, currency: btc, fixed: 4}
  sort_order: 1
  #visible: false     # default to true
- id: ethbtc
  code: 4
  #name: ETH/BTC      # default name
  base_unit: eth
  quote_unit: btc
  #price_group_fixed: 1 # aggregate price levels in orderbook
  bid: {fee: 0, currency: aud, fixed: 2}
  ask: {fee: 0, currency: eth, fixed: 4}
  sort_order: 1
  #visible: false     # default to true
- id: xrpbtc
  code: 5
  #name: XRP/BTC      # default name
  base_unit: xrp
  quote_unit: btc
  #price_group_fixed: 1 # aggregate price levels in orderbook
  bid: {fee: 0, currency: xrp, fixed: 2}
  ask: {fee: 0, currency: btc, fixed: 4}
  sort_order: 1
  #visible: false     # default to true
